### ISSUE TITLE
Mention availability of a built CSS file in the package

### ISSUE THREAD

**Issue by romaricpascal** [alphagov/govuk-frontend-docs#348] opened 2023-09-25 15:10 UTC
## What

Add a mention for the `govuk-frontend.min.css` file in our guidance:
- On the [Importing CSS assets and JavaScript](https://frontend.design-system.service.gov.uk/importing-css-assets-and-javascript/#import-css-assets-and-javascript) page
- Possibly on the [Get Started](https://frontend.design-system.service.gov.uk/get-started/#3-get-the-css-working) page as well, as copying a file (like we do for the JavaScript) is a simpler way to get started. Will have to be balanced with our preference for people only importing the parts they need (though that bit is buried in the [Importing CSS assets and JavaScript](https://frontend.design-system.service.gov.uk/importing-css-assets-and-javascript/#import-css-assets-and-javascript) page)

## Why

https://github.com/alphagov/govuk-frontend/pull/4240 adds a built CSS file to our package. It would be helpful for it to be listed in the frontend docs so people know to use it (if they don't have Sass on their project).

## Done when

- [x] Update the [Importing CSS assets and JavaScript](https://frontend.design-system.service.gov.uk/importing-css-assets-and-javascript/#import-css-assets-and-javascript) page
- [x] Decide whether to update the [Get Started](https://frontend.design-system.service.gov.uk/get-started/#3-get-the-css-working) page as well, as copying a file (like we do for the JavaScript) page and update content if necessary

**Comment by domoscargin** [comment] 2023-10-17 13:40
@romaricpascal We discussed in planning that this may be a duplicate of #3172

**Closed** 2023-10-30 10:04 UTC
